// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApc6X9ea-TXUYlerP5Abvh0Si6s9fDZrg',
    appId: '1:227350956692:web:b02c8356ceb12c0b25c281',
    messagingSenderId: '227350956692',
    projectId: 'wasil-task-46747',
    authDomain: 'wasil-task-46747.firebaseapp.com',
    storageBucket: 'wasil-task-46747.firebasestorage.app',
    measurementId: 'G-SJQZY5V173',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHw7RYOzEYBeZy_as3ocn5wQCLtC1VN8g',
    appId: '1:227350956692:android:13498169b058054825c281',
    messagingSenderId: '227350956692',
    projectId: 'wasil-task-46747',
    storageBucket: 'wasil-task-46747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyJGYalzjXHgxvake_jaKci17vobO2_Y',
    appId: '1:227350956692:ios:74dce0ca9267f34425c281',
    messagingSenderId: '227350956692',
    projectId: 'wasil-task-46747',
    storageBucket: 'wasil-task-46747.firebasestorage.app',
    iosClientId: '227350956692-ti8f6e7192rphmabp6u4i5bpn2huhoru.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasilFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmyJGYalzjXHgxvake_jaKci17vobO2_Y',
    appId: '1:227350956692:ios:74dce0ca9267f34425c281',
    messagingSenderId: '227350956692',
    projectId: 'wasil-task-46747',
    storageBucket: 'wasil-task-46747.firebasestorage.app',
    iosClientId: '227350956692-ti8f6e7192rphmabp6u4i5bpn2huhoru.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasilFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApc6X9ea-TXUYlerP5Abvh0Si6s9fDZrg',
    appId: '1:227350956692:web:6b3f9cd2260e032225c281',
    messagingSenderId: '227350956692',
    projectId: 'wasil-task-46747',
    authDomain: 'wasil-task-46747.firebaseapp.com',
    storageBucket: 'wasil-task-46747.firebasestorage.app',
    measurementId: 'G-NE9G5EH1R6',
  );
}
